In [1]:
import torch
torch.cuda.is_available()
x = torch.rand(5, 3)
print(x)

d:\work\personal-projects\pytorch-nlp\pytorch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[0.1798, 0.6248, 0.2278],
        [0.2981, 0.3528, 0.4206],
        [0.8528, 0.1899, 0.6302],
        [0.6498, 0.7147, 0.4099],
        [0.5166, 0.0357, 0.4708]])


In [3]:
#scalar
scalar = torch.tensor(21)
scalar

tensor(21)

In [5]:
#dimention of scalar
print(scalar.ndim)
#get tensor back to python int
print(scalar.item()) #=> only 0 dimention tensor can be converted into python scalar

0
21


In [6]:
#vector
vector = torch.tensor([11,21])
vector

tensor([11, 21])

In [8]:
#dimention of vector
print(vector.ndim)
print(vector.size())

1
torch.Size([2])


In [9]:
#MATRIX
MATRIX = torch.tensor([[1,2,3],[9,8,7]])
MATRIX

tensor([[1, 2, 3],
        [9, 8, 7]])

In [10]:
#dimention of MÂTRIX
print(MATRIX.ndim)
#size of MATRIX
print(MATRIX.size())

2
torch.Size([2, 3])


In [15]:
#TENSOR
TENSOR = torch.tensor([
                        [
                            [1,2,3],
                            [4,5,6],
                            [1,4,7],
                            [2,5,8]
                        ]
                      ]) 
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [1, 4, 7],
         [2, 5, 8]]])

In [16]:
#dimension of TENSOR
print(TENSOR.ndim)
#size of TENSOR
print(TENSOR.size())

3
torch.Size([1, 4, 3])


### Random tensor

In [20]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
print(random_tensor.ndim)
random_tensor

2


tensor([[0.9364, 0.6767, 0.0842, 0.5898],
        [0.8389, 0.9316, 0.7499, 0.8045],
        [0.0827, 0.7268, 0.5419, 0.9267]])

In [22]:
#create a random image of size (224,224,3)
random_image_tensor = torch.rand(size = (3,224,224))
print(random_image_tensor.ndim)
print(random_image_tensor.size())

3
torch.Size([3, 224, 224])


### Zeros and ones

In [25]:
#create of tensor of all zeros
zeros_tensor = torch.zeros(3,4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros_tensor.dtype

torch.float32

In [26]:
#create of tensor of all ones
ones_tensor = torch.ones(5,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones_tensor.dtype

torch.float32

### Create a range of tensors and tensor-like

In [37]:
#use torch.arange() - use to create a 1-d tensor
one_to_ten = torch.arange(start = 1,end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
#create tensor like
ten_zeros = torch.zeros_like(input =random_tensor)
ten_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor datatype
<b>Note</b>: Tensor datatype is one of the big 3 errors you will run into with PyTorch & deep learning:
1. Tensors not right data type
2. Tensors not right shape
3. Tensor not right device

In [41]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                                dtype =None, #what data type of tensor
                                device = None, #what device is the tensor on
                                require_grad = False) #whether or not to tracking gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [42]:
float_32_tensor.dtype

torch.float32

In [45]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [47]:
test_tensor = float_16_tensor * float_32_tensor
test_tensor.dtype

torch.float32

#### Getting information from tensor
1. Tensor not in right dtype - to do get datatype from a tensor, can use tensor.dtype
2. Tensor not in right shape - to get shape from a tensor, can use tensor.shape
3. Tensor not on the right device - to get device from a tensor, can use tensor.device

In [48]:
#create a tensor
test_tensor = torch.rand(5,4) 

In [49]:
print("dtype of tensor: ",test_tensor.dtype)
print("shape of tensor: ", test_tensor.shape)
print("device of tensor: ", test_tensor.device)

dtype of tensor:  torch.float32
shape of tensor:  torch.Size([5, 4])
device of tensor:  cpu


### Manipulate tensor
Tensor opertaion include:
* addition
* subtraction
* division
* multiplication (element wise)
* matrix multiplication


In [50]:
#create a tensor:
tensor = torch.tensor([4,5,6])
tensor+10

tensor([14, 15, 16])

In [51]:
tensor*10

tensor([40, 50, 60])

In [52]:
#try in-build function in pytorch
torch.mul(tensor,10)

tensor([40, 50, 60])

In [53]:
torch.add(tensor,10)

tensor([14, 15, 16])

### Matrix multiplication
There are 2 main ways to perform multiplication in neural network and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot-product)

There are 2 main rule need to sastify for the matrix multiplication:
1. The **inner dimention** must match:
* `(3,2) @ (3,2)` will not work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work
2. The resulting matrix must have the shape of **outter dimention**:
* `(3,2) @ (2,3)` will have shape (3,3)
* `(2,3) @ (3,5)` will have shape (2,5) 

In [54]:
#Element-wise multiplication
print(f"{tensor} * {tensor}")
print("Equal: ", tensor*tensor)

tensor([4, 5, 6]) * tensor([4, 5, 6])
Equal:  tensor([16, 25, 36])


In [56]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(77)

### one of the most common errors in deep learning: shape errors

In [58]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])


To fix the shape errors, we can manipulate the shape of one of the tensor using a **transpose**

A **transpose** switches the axes or dimentions of the given tensor

In [60]:
#torch.mm = torch.matmul (it's an alias for less code)
print(f"shape of tensor_A: {tensor_A.shape}; shape of tensor_B: {tensor_B.shape}")
print(f"shape of tensor_A: {tensor_A.shape}; shape of tensor_B Transpose: {tensor_B.T.shape}")
print(f"shape of tensor multiply by tensor_A and tensor_B Transpose {torch.matmul(tensor_A, tensor_B.T).shape}")
torch.matmul(tensor_A, tensor_B.T)

shape of tensor_A: torch.Size([3, 2]); shape of tensor_B: torch.Size([3, 2])
shape of tensor_A: torch.Size([3, 2]); shape of tensor_B Transpose: torch.Size([2, 3])
shape of tensor multiply by tensor_A and tensor_B Transpose torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Reshaping, stacking, squeezing and unsquezzing tenssors

* reshaping - reshape an input tensor to a define shape
* view - Return a view of an input tensor of a certain shape but keep the same memory as an original tensor
* stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* squeeze - remove all `1` dimensions from a tensor
* unsqueeze - add `1` dimensions to a tensor
* permute - return a view of the input with the dimensions permuted (swapped) in a certain way

In [2]:
import torch


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
x= torch.arange(1.,13)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [22]:
#reshape
x_reshaped = x.reshape(3,2,2)
x_reshaped, x_reshaped.shape

(tensor([[[10., 10.],
          [ 3.,  4.]],
 
         [[10., 10.],
          [ 7.,  8.]],
 
         [[10., 10.],
          [11., 12.]]]),
 torch.Size([3, 2, 2]))

In [25]:
#view - the parameter using view share the same memory with the original
z = x.view(3,2,2)
print(z)
#change the value of z
z[:,0,1] = 10
print(z)
print(x)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor([[[ 1., 10.],
         [ 3.,  4.]],

        [[ 5., 10.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor([ 1., 10.,  3.,  4.,  5., 10.,  7.,  8.,  9., 10., 11., 12.])


In [35]:
#stack tensor on each other
x= torch.arange(1.,13)
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [40]:
#squeeze
tmp_x = x.reshape(1,4,3,1)
print(tmp_x.shape)
print(tmp_x)
x_squeezed = torch.squeeze(tmp_x)
print(x_squeezed)
print(x_squeezed.shape)

torch.Size([1, 4, 3, 1])
tensor([[[[ 1.],
          [ 2.],
          [ 3.]],

         [[ 4.],
          [ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.],
          [ 9.]],

         [[10.],
          [11.],
          [12.]]]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


In [49]:
#unsqueeze
x_unsqueezed = torch.unsqueeze(x_squeezed,dim =1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[[ 1.,  2.,  3.]],
 
         [[ 4.,  5.,  6.]],
 
         [[ 7.,  8.,  9.]],
 
         [[10., 11., 12.]]]),
 torch.Size([4, 1, 3]))

In [54]:
#torch.permute - rearange the dimensions of a target tensor in a specific order
x_original = torch.rand(size=(224,224,3)) # [height, width, color channel]

#permute the original tensor to rearrange the axis (or dims) order
x_permuted = x_original.permute(2,0,1) # [color channel, height, width]

print(f"Previous shape {x_original.shape}")
print(f"New shape {x_permuted.shape}")
print(f"Reshape shape {x_original.reshape(3,224,224).shape}")

Previous shape torch.Size([224, 224, 3])
New shape torch.Size([3, 224, 224])
Reshape shape torch.Size([3, 224, 224])


In [57]:
print(x_permuted[0,0,0])
print(x_original.reshape(3,224,224)[0,0,0])

tensor(0.9716)
tensor(0.9716)


In [62]:
#indexing
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
#idnex to get the value 9
print(x[0,2,2])
#index to get 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


### Reproducibility (trying to take random out of random)
To reduce the randomness in neural network and Pytorch come with a concept of ***random seed**

Essentially what the random seed does is "flavour" the randomess

In [69]:
import torch
random_tensor_A = torch.rand(3,3)
random_tensor_B = torch.rand(3,3)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6844, 0.5991, 0.2753],
        [0.0844, 0.6459, 0.0316],
        [0.7579, 0.0040, 0.0330]])
tensor([[0.2269, 0.5631, 0.5557],
        [0.0326, 0.8227, 0.6887],
        [0.2077, 0.2805, 0.9404]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [70]:
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,3)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Running tensor and pytorch object on the GPUs (and making faster computation)

### 1. Getting a GPU
1. Esiest - Use google colab for free GPU (options to upgrae as well)
2. Use personal GPUs - require a little bit of setup and investment of purchasing a GPU.
3. Use cloud computing - GCP, AWS, Azure, these services allow you tor rent computer on the cloud and access them

For 2, and 3 Pytorch + GPU driver (CUDA) takes a little bits of setting up, to do this, refer to Pytorch setup documentation 

### 2. Check for Pytorch GPU access

In [72]:
###Check the gpu access
import torch
torch.cuda.is_available()

True

For Pytorch, since it's available of running compute on both GPU and CPU, it's best practice to setup device agnostic code

E.g. run on GPU if available, else default CPU 

In [80]:
###Setup the device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [81]:
###Check the number of gpu device
torch.cuda.device_count()

1

### 3. Putting tensor/model on GPU

In [78]:
tensor = torch.tensor([1,2,3,4])
print(tensor, tensor.device)

tensor([1, 2, 3, 4]) cpu


In [82]:
##moving tensor to gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4], device='cuda:0')

### 4. Moving tensor back to cpu

In [84]:
#If tensor is on gpu, can't transform it to numpy
#first set the tensor to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.numpy()

array([1, 2, 3, 4], dtype=int64)

### Ecercite